# Site settings
title: Philos
email: ping@philos.io
description: > # this means to ignore newlines until "baseurl:"
  We will be writting about technical topics we're working on at Philos Lab.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://philos.io" # the base hostname & protocol for your site
twitter_username: philos_io
github_username:  Philos-io

# Build settings
markdown: kramdown
